# Generated by Django 4.2.7 on 2023-12-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
