version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: gunicorn pastebin.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    environment:
      - DJANGO_LOG_LEVEL=info
  db:
    image: postgres:15
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=pastebin
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  celery:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: bash -c "celery -A hash_generator worker -P eventlet --loglevel=info"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web
  celery_beat_hash_generator:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: bash -c "celery -A hash_generator beat -l info"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web
      - celery
  celery_beat_autodelete:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: bash -c "celery -A api beat -l info"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web
      - celery
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
