version: '3.9'

services:
  auth_service:
    build:
      context: ./pastebin_authentication_service/
    env_file:
      - ./pastebin_authentication_service/.env.test
    ports:
      - "81:81"
    depends_on:
      - auth_db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 81"
  auth_db:
    image: postgres:15
    volumes:
      - auth_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pastebin_authentication_service
    command: ["postgres", "-c", "port=5400"]
  pastebin_nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
  web:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - memcached
  db:
    image: postgres:15
    volumes:
     - main_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=pastebin
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  celery:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: bash -c "celery -A hash_generator worker -P eventlet --loglevel=info"
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery_beat_hash_generator:
    build:
      context: .
      dockerfile: pastebin/Dockerfile
    command: bash -c "celery -A hash_generator beat -l info"
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - celery
#  celery_beat_autodelete:
#    build:
#      context: .
#      dockerfile: pastebin/Dockerfile
#    command: bash -c "celery -A notes beat -l info"
#    env_file:
#      - ./.env
#    depends_on:
#      - redis
#      - web
#      - celery
volumes:
  main_data:
  auth_data: