# Generated by Django 4.2.7 on 2024-05-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_comment_note_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmetadata',
            name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='usercommentrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercommentrating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentMetaData',
        ),
        migrations.DeleteModel(
            name='UserCommentRating',
        ),
    ]
