# Generated by Django 4.2.7 on 2024-06-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_commentmetadata_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_link', models.CharField(db_index=True, max_length=200, unique=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
