# Generated by Django 4.2.7 on 2024-06-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_privatelink_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelink',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
