# Generated by Django 4.2.7 on 2023-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemetadata',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
