# Generated by Django 4.2.7 on 2024-02-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_options_comment_level_comment_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='note_comment_id',
        ),
    ]
