# Generated by Django 4.2.7 on 2023-11-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
