# Generated by Django 4.2.7 on 2023-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notemetadata_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='availability',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default=1),
            preserve_default=False,
        ),
    ]
