# Generated by Django 4.2.7 on 2023-11-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_content_note_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='time_update',
        ),
        migrations.AddField(
            model_name='note',
            name='hash_link',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
