# Generated by Django 4.2.7 on 2023-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_time_update_note_hash_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hash_link',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
