# Generated by Django 4.2.7 on 2023-12-16 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_userstars'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_stars',
            field=models.ManyToManyField(related_name='starred_notes', through='api.UserStars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userstars',
            unique_together={('user', 'note')},
        ),
    ]
