# Generated by Django 4.2.7 on 2023-12-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usercommentrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='commentmetadata',
            name='comment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='api.comment'),
            preserve_default=False,
        ),
    ]
