# Generated by Django 4.2.7 on 2023-12-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_comment_meta_data_commentmetadata_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='notemetadata',
            name='note',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='api.note'),
            preserve_default=False,
        ),
    ]
