# Generated by Django 4.2.7 on 2024-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='availability',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public'),
        ),
    ]
